"""
First-run wizard — produces a ``ubik.yaml`` + ``.env.example`` from a
short interactive Q&A.

Pure rendering lives in ``render_yaml`` / ``render_env_example`` so tests
can assemble a ``WizardAnswers`` directly and verify the output without
mocking prompts.
"""
from __future__ import annotations

import re
import subprocess
from dataclasses import dataclass, field
from pathlib import Path

from rich.console import Console
from rich.prompt import Confirm, IntPrompt, Prompt


# ── Provider presets ─────────────────────────────────────────────────────
# Each preset maps to a researcher.llm block + which env var users must
# set in their .env. The ``model`` is a sane default, freely overridable.

@dataclass(frozen=True, slots=True)
class ProviderPreset:
    key: str
    label: str
    provider: str
    base_url: str | None
    api_key_env: str
    model: str


PRESETS: list[ProviderPreset] = [
    # ── Z.AI ────────────────────────────────────────────────────────────
    ProviderPreset(
        key="zai",
        label="Z.AI · GLM Coding Plan  ★ recommended (free with annual sub, SOTA SWE-Bench Pro)",
        provider="openai_compatible",
        base_url="https://api.z.ai/api/coding/paas/v4",
        api_key_env="Z_AI_API_KEY",
        model="glm-5.1",
    ),
    ProviderPreset(
        key="zai-standard",
        label="Z.AI · GLM (standard API, pay-per-token)",
        provider="openai_compatible",
        base_url="https://api.z.ai/api/paas/v4",
        api_key_env="Z_AI_API_KEY",
        model="glm-4.6",
    ),
    # ── Anthropic ──────────────────────────────────────────────────────
    ProviderPreset(
        key="anthropic",
        label="Anthropic · Claude Sonnet 4.6",
        provider="anthropic",
        base_url=None,
        api_key_env="ANTHROPIC_API_KEY",
        model="claude-sonnet-4-6",
    ),
    ProviderPreset(
        key="anthropic-opus",
        label="Anthropic · Claude Opus 4.7  (1M context)",
        provider="anthropic",
        base_url=None,
        api_key_env="ANTHROPIC_API_KEY",
        model="claude-opus-4-7",
    ),
    # ── Chinese frontier ───────────────────────────────────────────────
    ProviderPreset(
        key="kimi",
        label="Moonshot · Kimi K2.6  (long-context reasoning)",
        provider="openai_compatible",
        base_url="https://api.moonshot.ai/v1",
        api_key_env="MOONSHOT_API_KEY",
        model="kimi-k2",
    ),
    ProviderPreset(
        key="minimax",
        label="MiniMax · M2.7",
        provider="openai_compatible",
        base_url="https://api.minimaxi.chat/v1",
        api_key_env="MINIMAX_API_KEY",
        model="MiniMax-M2",
    ),
    # ── Western fallbacks ──────────────────────────────────────────────
    ProviderPreset(
        key="openai",
        label="OpenAI · GPT-4o",
        provider="openai",
        base_url=None,
        api_key_env="OPENAI_API_KEY",
        model="gpt-4o",
    ),
    ProviderPreset(
        key="ollama",
        label="Ollama · local (llama3.1) — no API key needed",
        provider="openai_compatible",
        base_url="http://localhost:11434/v1",
        api_key_env="OLLAMA_API_KEY",  # value is irrelevant; ollama ignores
        model="llama3.1",
    ),
]


def preset_by_key(key: str) -> ProviderPreset:
    for p in PRESETS:
        if p.key == key:
            return p
    raise KeyError(f"unknown preset {key!r}; choose from {[p.key for p in PRESETS]}")


# ── Answers + rendering ──────────────────────────────────────────────────


@dataclass(slots=True)
class WizardAnswers:
    project_name: str
    repo_path: str
    default_branch: str
    preset: ProviderPreset
    bridge_token_env: str = "TELEGRAM_BOT_TOKEN"
    bridge_chat_id_env: str = "TELEGRAM_CHAT_ID"
    approver_chat_ids: list[int] = field(default_factory=list)
    github_repo: str = ""  # e.g. "getubik/ubik"
    test_command: str | None = None
    max_proposals_per_day: int = 20
    daily_usd_cap: float = 15.0
    notebook_path: str = "./research"
    daily_at: str = "09:00"


def render_yaml(a: WizardAnswers) -> str:
    """Produce a fully-honest ubik.yaml — every field round-trips through the loader."""
    base_url_line = (
        f'    base_url: "{a.preset.base_url}"\n'
        if a.preset.base_url
        else "    base_url: null\n"
    )
    test_line = (
        f'  test_command: "{a.test_command}"\n' if a.test_command else "  test_command: null\n"
    )
    approvers = (
        "\n".join(f"    - {cid}" for cid in a.approver_chat_ids)
        or "    # - 123456789  # add your Telegram chat id(s) here"
    )
    return f"""# ─────────────────────────────────────────────────────────────────────
# Generated by `ubik init`. Edit freely — every field round-trips
# through ubik/core/config.py. Roadmap-only fields live in docs/roadmap.md.
# ─────────────────────────────────────────────────────────────────────

project:
  name: "{a.project_name}"
  repo_path: "{a.repo_path}"
  default_branch: "{a.default_branch}"

researcher:
  llm:
    provider: "{a.preset.provider}"
{base_url_line}    api_key_env: "{a.preset.api_key_env}"
    model: "{a.preset.model}"
    thinking: true
    max_tokens: 8000
  schedule:
    daily_at: "{a.daily_at}"
    pulse_every_minutes: 0

executor:
  type: "aider"
  sandbox:
    worktree_dir: "./.ubik-worktrees"
    cost_cap_usd: 5.0
    time_cap_minutes: 15
  guardrails:
    cannot_push_to: ["main", "master", "production"]
    require_tests: true
    require_pr_review: true

bridge:
  type: "telegram"
  token_env: "{a.bridge_token_env}"
  chat_id_env: "{a.bridge_chat_id_env}"
  approver_chat_ids:
{approvers}
  rate_limit:
    max_pushes_per_hour: 5
    cooldown_minutes_per_proposal: 60

verifier:
{test_line}  build_command: null
  smoke_command: null
  pr:
    provider: "github"
    repo: "{a.github_repo}"
    base_branch: "{a.default_branch}"
    auto_create: true

notebook:
  storage: "filesystem"
  path: "{a.notebook_path}"

cost:
  daily_usd_cap: {a.daily_usd_cap}
  alert_at_percent: 80
  track_only: false
  max_proposals_per_day: {a.max_proposals_per_day}
"""


def render_env_example(a: WizardAnswers) -> str:
    """Companion .env.example — the secrets ubik.yaml refers to by env-var name."""
    lines = [
        "# Generated by `ubik init`. Copy to `.env` and fill in the values.",
        "# `.env` is in .gitignore by default; never commit secrets.",
        "",
        f"# LLM provider: {a.preset.label}",
        f"{a.preset.api_key_env}=",
        "",
        "# Telegram bridge — create a bot via @BotFather, then send it /start",
        "# from your account and visit https://api.telegram.org/bot<TOKEN>/getUpdates",
        "# to find your chat id.",
        f"{a.bridge_token_env}=",
        f"{a.bridge_chat_id_env}=",
        "",
        "# GitHub — verifier needs either `gh` on PATH (preferred) OR this token.",
        "GITHUB_TOKEN=",
    ]
    return "\n".join(lines) + "\n"


# ── Interactive flow ─────────────────────────────────────────────────────


def autodetect_default_branch(repo: Path) -> str:
    """Read git's HEAD reference; fall back to 'main'."""
    try:
        out = subprocess.run(
            ["git", "symbolic-ref", "refs/remotes/origin/HEAD", "--short"],
            cwd=str(repo), capture_output=True, text=True, timeout=3, check=False,
        )
        if out.returncode == 0:
            ref = out.stdout.strip()
            if "/" in ref:
                return ref.split("/", 1)[1]
    except (OSError, subprocess.SubprocessError):
        pass
    return "main"


_REPO_SLUG_RE = re.compile(r"github\.com[:/](?P<slug>[^/]+/[^/.]+)(?:\.git)?$")


def autodetect_github_slug(repo: Path) -> str:
    """origin URL → 'org/repo' or empty string."""
    try:
        out = subprocess.run(
            ["git", "remote", "get-url", "origin"],
            cwd=str(repo), capture_output=True, text=True, timeout=3, check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return ""
    if out.returncode != 0:
        return ""
    m = _REPO_SLUG_RE.search((out.stdout or "").strip())
    return m.group("slug") if m else ""


def interactive_wizard(*, default_repo: Path, console: Console) -> WizardAnswers:
    """Prompt the user; return validated answers. Side-effect: prints to console."""
    console.print()
    console.print("[bold]🤫 Ubik · first-run wizard[/bold]")
    console.print(
        "[dim]Six questions, all with sensible defaults. "
        "You can edit ubik.yaml afterwards.[/dim]\n"
    )

    repo = default_repo.resolve()
    project_name = Prompt.ask("Project name", default=repo.name)
    repo_path = Prompt.ask(
        "Repo path Ubik should watch", default=str(repo)
    )
    default_branch = Prompt.ask(
        "Default branch", default=autodetect_default_branch(repo)
    )

    # LLM provider
    console.print("\n[bold]LLM provider[/bold]")
    for i, p in enumerate(PRESETS, 1):
        console.print(f"  [cyan]{i}[/cyan]. {p.label}")
    idx = IntPrompt.ask(
        "Choose", default=1, choices=[str(i) for i in range(1, len(PRESETS) + 1)]
    )
    preset = PRESETS[idx - 1]

    # Bridge
    console.print("\n[bold]Telegram bridge[/bold] [dim](only bridge in 0.1.0)[/dim]")
    chat_ids_raw = Prompt.ask(
        "Approver chat id(s), comma-separated [dim](leave blank to fill in later)[/dim]",
        default="",
    )
    approver_chat_ids = [
        int(x) for x in (s.strip() for s in chat_ids_raw.split(",")) if x.isdigit()
    ]

    # Verifier — GitHub
    console.print("\n[bold]GitHub verifier[/bold]")
    github_repo = Prompt.ask(
        "Repo slug (org/repo) for PRs", default=autodetect_github_slug(repo)
    )
    test_command = Prompt.ask(
        "Test command [dim](blank = skip tests during executor run)[/dim]",
        default="pytest -q",
    )

    # Cost caps
    console.print("\n[bold]Spending guards[/bold]")
    max_proposals = IntPrompt.ask("Max proposals per day", default=20)
    daily_usd = float(Prompt.ask("Daily USD cap (informational)", default="15"))

    daily_at = Prompt.ask("Daily audit time (HH:MM, local)", default="09:00")

    return WizardAnswers(
        project_name=project_name,
        repo_path=repo_path,
        default_branch=default_branch,
        preset=preset,
        approver_chat_ids=approver_chat_ids,
        github_repo=github_repo,
        test_command=test_command or None,
        max_proposals_per_day=max_proposals,
        daily_usd_cap=daily_usd,
        notebook_path="./research",
        daily_at=daily_at,
    )
